f1<-factor(sample(LETTERS,size=6,replace=TRUE))
f2<-factor(sample(LETTERS,size=4,replace=TRUE))
print(f1)
print(f2)
f=factor(c(levels(f1)[f1],levels(f2)[f2]))
print("After concatination factors becomes:")
print(f)
